"""update table penerima

Revision ID: 0578a1bacb78
Revises: ca4fcde3a338
Create Date: 2025-08-30 14:15:58.015775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0578a1bacb78'
down_revision = 'ca4fcde3a338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('tanggal_masuk',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('tanggal_approve')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_approve', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('tanggal_masuk',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
