"""tambah kolom kategori di datadiripenerima

Revision ID: 07d87748cca0
Revises: 6ce60d4df746
Create Date: 2025-10-04 20:07:35.413387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d87748cca0'
down_revision = '6ce60d4df746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', sa.Enum('buku', 'pakaian', 'furniture', 'elektronik', 'peralatan dapur', name='kategori_enum'), server_default='buku', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    # ### end Alembic commands ###
