"""table dokumentasi

Revision ID: 14525fd0bdd9
Revises: da0effe69d71
Create Date: 2025-12-04 15:09:11.161014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14525fd0bdd9'
down_revision = 'da0effe69d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dokumentasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('ukuran_file', sa.String(length=255), nullable=False),
    sa.Column('tanggal_dokumendasi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_barang', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('approve', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_approve', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_reject', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_pengajuan', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pesan_reject', sa.String(length=255), nullable=True))
        batch_op.drop_column('jumlah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('pesan_reject')
        batch_op.drop_column('tanggal_pengajuan')
        batch_op.drop_column('tanggal_reject')
        batch_op.drop_column('tanggal_approve')
        batch_op.drop_column('approve')
        batch_op.drop_column('nama_barang')

    op.drop_table('dokumentasi')
    # ### end Alembic commands ###
