"""rename lokasi jadi alamat

Revision ID: 1d7f061057ea
Revises: 654958f1336c
Create Date: 2025-10-21 04:53:36.475723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7f061057ea'
down_revision = '654958f1336c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alamat', sa.String(length=100), nullable=False))
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('alamat')

    # ### end Alembic commands ###
