"""tambahkan kondisi barang pada table barang

Revision ID: 299a44e47065
Revises: 07d87748cca0
Create Date: 2025-10-06 20:05:18.557942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299a44e47065'
down_revision = '07d87748cca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kondisi_barang', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('kondisi_barang')

    # ### end Alembic commands ###
