"""rename kolom approve to status

Revision ID: 2a42dc60c687
Revises: 8ca4eb476230
Create Date: 2025-12-24 06:31:25.674286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a42dc60c687'
down_revision = '8ca4eb476230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('approve')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
