"""ubah tipe gambar_barang ke string

Revision ID: 2c5fc3f78636
Revises: 0578a1bacb78
Create Date: 2025-09-03 13:14:34.685049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c5fc3f78636'
down_revision = '0578a1bacb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('gambar_barang',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.alter_column('layak',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.alter_column('layak',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('gambar_barang',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               existing_nullable=True)

    # ### end Alembic commands ###
