"""rename kolom penerima_id di  table dokumenetasi

Revision ID: 39630b33a608
Revises: d7135f3722d6
Create Date: 2025-12-08 17:22:25.548801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39630b33a608'
down_revision = 'd7135f3722d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penerima_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'data_diri_penerima', ['penerima_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('penerima_id')

    # ### end Alembic commands ###
