"""menambahkan table hasil klasifikasi

Revision ID: 49939d99ca21
Revises: e71e04d0fcab
Create Date: 2025-09-07 05:51:57.689972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49939d99ca21'
down_revision = 'e71e04d0fcab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_klasifikasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_penerima', sa.Integer(), nullable=False),
    sa.Column('id_data_diri_penerima', sa.Integer(), nullable=False),
    sa.Column('layak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_data_diri_penerima'], ['data_diri_penerima.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_penerima'], ['penerima.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_klasifikasi')
    # ### end Alembic commands ###
