"""ubah id_user di barang -> id_donatur

Revision ID: 49d4da6d2ab2
Revises: ecb52da31ace
Create Date: 2025-10-10 11:10:16.401034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d4da6d2ab2'
down_revision = 'ecb52da31ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_donatur', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('barang_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('barang_id_user_fkey'), 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_donatur')

    # ### end Alembic commands ###
