"""tambah kolom donasi_terkumpul

Revision ID: 4a920db9cbff
Revises: 9705f05e3854
Create Date: 2026-02-11 20:47:14.309987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a920db9cbff'
down_revision = '9705f05e3854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donasi_terkumpul', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_column('donasi_terkumpul')

    # ### end Alembic commands ###
