"""tambahkan delete cascade di table hasil_rekomendasi

Revision ID: 4b97a0655bf8
Revises: 71e19748a8a2
Create Date: 2025-09-06 18:09:24.763416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b97a0655bf8'
down_revision = '71e19748a8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_id_data_diri_penerima_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'penerima', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'data_diri_penerima', ['id_data_diri_penerima'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_id_penerima_fkey'), 'penerima', ['id_penerima'], ['id'])
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_id_data_diri_penerima_fkey'), 'data_diri_penerima', ['id_data_diri_penerima'], ['id'])

    # ### end Alembic commands ###
