"""tambah foreign key pada table donasi dan barang

Revision ID: 4f2128219b85
Revises: cdd2319ca02b
Create Date: 2025-08-27 15:49:20.557173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f2128219b85'
down_revision = 'cdd2319ca02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('tanggal_masuk',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_barang', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))
        batch_op.alter_column('tanggal_donasi',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_foreign_key(None, 'barang', ['id_barang'], ['id'])
        batch_op.drop_column('jumlah_donasi')
        batch_op.drop_column('jenis_donasi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_donasi', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jumlah_donasi', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tanggal_donasi',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('id_barang')

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('tanggal_masuk',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
