"""tambah relasi notif ke donasi

Revision ID: 52b11b3ddba1
Revises: a5f04d8a83bc
Create Date: 2025-10-11 17:30:31.889564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b11b3ddba1'
down_revision = 'a5f04d8a83bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_donasi', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'donasi', ['id_donasi'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_donasi')

    # ### end Alembic commands ###
