"""hapus kategori di model tabel daridiripenerima

Revision ID: 540c174f57a1
Revises: c12898b16369
Create Date: 2026-01-04 10:36:02.962283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '540c174f57a1'
down_revision = 'c12898b16369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', postgresql.ENUM('buku', 'pakaian', 'furniture', 'elektronik', 'peralatan dapur', name='kategori_enum'), server_default=sa.text("'buku'::kategori_enum"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
