"""tambah kolom lokasi pada datadiripenerima

Revision ID: 654958f1336c
Revises: c48c240183db
Create Date: 2025-10-21 04:51:12.639114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654958f1336c'
down_revision = 'c48c240183db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_column('lokasi')

    # ### end Alembic commands ###
