"""tambah reject_tanggal di table donasi

Revision ID: 66d891cd46ea
Revises: 49d4da6d2ab2
Create Date: 2025-10-10 16:01:40.224954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d891cd46ea'
down_revision = '49d4da6d2ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_reject', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_column('tanggal_reject')

    # ### end Alembic commands ###
