"""tambahkan kolom status di register_login

Revision ID: 6ce60d4df746
Revises: 8b75138bbf29
Create Date: 2025-10-03 14:35:16.344831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce60d4df746'
down_revision = '8b75138bbf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('rejected', 'approved', 'pending', name='permission_enum'), server_default='pending', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
