"""tambah kolom jumlah di table barang

Revision ID: 6e2093bb8ecb
Revises: 4a920db9cbff
Create Date: 2026-02-13 14:45:57.321175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2093bb8ecb'
down_revision = '4a920db9cbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_barang', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('jumlah_barang')

    # ### end Alembic commands ###
