"""tambah ondelete cascade

Revision ID: 71e19748a8a2
Revises: 2c5fc3f78636
Create Date: 2025-09-06 18:04:17.354940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e19748a8a2'
down_revision = '2c5fc3f78636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('barang_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'donatur', ['id_donatur'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.alter_column('id_penerima',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('data_diri_penerima_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'penerima', ['id_penerima'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('donasi_id_barang_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('donasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('donasi_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'barang', ['id_barang'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'penerima', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'donatur', ['id_donatur'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('donasi_id_donatur_fkey'), 'donatur', ['id_donatur'], ['id'])
        batch_op.create_foreign_key(batch_op.f('donasi_id_penerima_fkey'), 'penerima', ['id_penerima'], ['id'])
        batch_op.create_foreign_key(batch_op.f('donasi_id_barang_fkey'), 'barang', ['id_barang'], ['id'])

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('data_diri_penerima_id_penerima_fkey'), 'penerima', ['id_penerima'], ['id'])
        batch_op.alter_column('id_penerima',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('barang_id_donatur_fkey'), 'donatur', ['id_donatur'], ['id'])

    # ### end Alembic commands ###
