"""ubah id_register to id_user

Revision ID: 7214aad37d07
Revises: 74dc5cea9e17
Create Date: 2025-09-29 13:53:18.918752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7214aad37d07'
down_revision = '74dc5cea9e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('hasil_klasifikasi_id_register_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_register')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_register', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_klasifikasi_id_register_fkey'), 'register_login', ['id_register'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
