"""ubah tipe kolom jadi nullable = True

Revision ID: 731fdd03a895
Revises: aad26050c17b
Create Date: 2026-01-01 16:39:14.028239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '731fdd03a895'
down_revision = 'aad26050c17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'donatur', 'penerima', name='role_enum'),
               nullable=True,
               existing_server_default=sa.text("'admin'::role_enum"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('rejected', 'approved', 'pending', name='permission_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::permission_enum"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('rejected', 'approved', 'pending', name='permission_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::permission_enum"))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'donatur', 'penerima', name='role_enum'),
               nullable=False,
               existing_server_default=sa.text("'admin'::role_enum"))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
