"""add id_data_diri

Revision ID: 83dc5bf8cc25
Revises: af8fe97fdf3f
Create Date: 2025-09-29 17:09:29.814379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dc5bf8cc25'
down_revision = 'af8fe97fdf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_data_diri', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'data_diri_penerima', ['id_data_diri'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_data_diri')

    # ### end Alembic commands ###
