"""hapus kolom status di register_login

Revision ID: 8b75138bbf29
Revises: 47ca00830fa0
Create Date: 2025-10-03 14:33:56.834023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b75138bbf29'
down_revision = '47ca00830fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('rejected', 'approved', name='permission_enum'), server_default=sa.text("'approved'::permission_enum"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
