"""tambah kolom jenis barang di table pengajuan

Revision ID: 8ca4eb476230
Revises: bc7192e14ea6
Create Date: 2025-12-24 03:46:12.521817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca4eb476230'
down_revision = 'bc7192e14ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_barang', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.drop_column('jenis_barang')

    # ### end Alembic commands ###
