"""tambah jumlah pada tabel pengajuan

Revision ID: 9705f05e3854
Revises: 540c174f57a1
Create Date: 2026-02-05 20:25:01.925376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9705f05e3854'
down_revision = '540c174f57a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.drop_column('jumlah')

    # ### end Alembic commands ###
