"""menambah id_penerima pada table barang

Revision ID: 9a57fa0999e2
Revises: cd8b0a515f2e
Create Date: 2025-12-17 18:23:31.296084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a57fa0999e2'
down_revision = 'cd8b0a515f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['id_penerima'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_penerima')

    # ### end Alembic commands ###
