"""tambah id_penerima dan id_barang di table notif

Revision ID: a5f04d8a83bc
Revises: c3b1faa3e760
Create Date: 2025-10-11 17:21:27.130253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f04d8a83bc'
down_revision = 'c3b1faa3e760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_barang', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('notifikasi_id_admin_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'barang', ['id_barang'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_admin', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifikasi_id_admin_fkey'), 'register_login', ['id_admin'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_barang')
        batch_op.drop_column('id_penerima')

    # ### end Alembic commands ###
