"""sync database

Revision ID: aa0a1def11c9
Revises: 
Create Date: 2026-03-14 21:03:48.026051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa0a1def11c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumentasi')
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('barang_id_penerima_fkey'), type_='foreignkey')
        batch_op.drop_column('id_penerima')
        batch_op.drop_column('jumlah_barang')

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', sa.Enum('buku', 'pakaian', 'furniture', 'elektronik', 'peralatan dapur', name='kategori_enum'), server_default='buku', nullable=False))
        batch_op.add_column(sa.Column('jumlah', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kebutuhan', sa.String(length=100), nullable=True))

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_column('donasi_terkumpul')

    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve', sa.Boolean(), nullable=True))
        batch_op.alter_column('jenis_barang',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('jumlah')
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'donatur', 'penerima', name='role_enum'),
               nullable=False,
               existing_server_default=sa.text("'admin'::role_enum"))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('rejected', 'approved', 'pending', name='permission_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::permission_enum"))
        batch_op.drop_column('edit_stamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('rejected', 'approved', 'pending', name='permission_enum'),
               nullable=True,
               existing_server_default=sa.text("'pending'::permission_enum"))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'donatur', 'penerima', name='role_enum'),
               nullable=True,
               existing_server_default=sa.text("'admin'::role_enum"))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jumlah', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('jenis_barang',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('approve')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donasi_terkumpul', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_column('jenis_kebutuhan')
        batch_op.drop_column('jumlah')
        batch_op.drop_column('kategori')

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_barang', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('barang_id_penerima_fkey'), 'users', ['id_penerima'], ['id'], ondelete='CASCADE')

    op.create_table('dokumentasi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ukuran_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tanggal_dokumentasi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_donatur', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_donatur'], ['users.id'], name=op.f('dokumentasi_id_donatur_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dokumentasi_pkey'))
    )
    # ### end Alembic commands ###
