"""tambah kolom tanggal edit

Revision ID: aad26050c17b
Revises: 2a42dc60c687
Create Date: 2026-01-01 15:39:18.160292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad26050c17b'
down_revision = '2a42dc60c687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_stamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('edit_stamp')

    # ### end Alembic commands ###
