"""lagi lagi dan lagi

Revision ID: af8fe97fdf3f
Revises: 7bf2423c9183
Create Date: 2025-09-29 17:01:53.880839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8fe97fdf3f'
down_revision = '7bf2423c9183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('data_diri_penerima_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_penerima')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('donasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('donasi_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_donatur')
        batch_op.drop_column('id_penerima')

    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('hasil_klasifikasi_id_data_diri_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('hasil_klasifikasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_data_diri')
        batch_op.drop_column('id_penerima')

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_id_donatur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_donatur')
        batch_op.drop_column('id_penerima')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_donatur', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_id_donatur_fkey'), 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_data_diri', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_klasifikasi_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('hasil_klasifikasi_id_data_diri_fkey'), 'data_diri_penerima', ['id_data_diri'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_donatur', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('donasi_id_donatur_fkey'), 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('donasi_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('data_diri_penerima_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
