"""tambah metode pengiriman di Donasi

Revision ID: b1107d2b7939
Revises: e4ebb07e0304
Create Date: 2025-10-14 20:53:39.107126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1107d2b7939'
down_revision = 'e4ebb07e0304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.alter_column('metode_pengiriman',
               existing_type=postgresql.ENUM('drop_in', 'drop_off', name='metode_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.alter_column('metode_pengiriman',
               existing_type=postgresql.ENUM('drop_in', 'drop_off', name='metode_enum'),
               nullable=True)

    # ### end Alembic commands ###
