"""tambahkan kolom pasif delete

Revision ID: b51fba2f511b
Revises: 49939d99ca21
Create Date: 2025-09-10 12:39:30.489594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51fba2f511b'
down_revision = '49939d99ca21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donatur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasif_delete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasif_deleter', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.drop_column('pasif_deleter')

    with op.batch_alter_table('donatur', schema=None) as batch_op:
        batch_op.drop_column('pasif_delete')

    # ### end Alembic commands ###
