"""hapus jenis_kebutuhan di table pengajuan

Revision ID: bc7192e14ea6
Revises: 9a57fa0999e2
Create Date: 2025-12-24 00:22:58.543734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7192e14ea6'
down_revision = '9a57fa0999e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar_barang', sa.String(length=255), nullable=True))
        batch_op.drop_column('jenis_barang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_barang', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('gambar_barang')

    # ### end Alembic commands ###
