"""true false

Revision ID: bd29887b4e6a
Revises: 1d7f061057ea
Create Date: 2025-10-21 11:58:02.880186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd29887b4e6a'
down_revision = '1d7f061057ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
