"""tambahkan metode pengiriman dan null pada donasi

Revision ID: bfaa8099b029
Revises: b1107d2b7939
Create Date: 2025-10-15 14:13:51.756067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfaa8099b029'
down_revision = 'b1107d2b7939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.alter_column('metode_pengiriman',
               existing_type=postgresql.ENUM('pick_up', 'drop_in', name='metode_enum'),
               nullable=True,
               existing_server_default=sa.text("'pick_up'::metode_enum"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.alter_column('metode_pengiriman',
               existing_type=postgresql.ENUM('pick_up', 'drop_in', name='metode_enum'),
               nullable=False,
               existing_server_default=sa.text("'pick_up'::metode_enum"))

    # ### end Alembic commands ###
