"""hapus jenis kebutuhan di model tabel datadiri

Revision ID: c12898b16369
Revises: 731fdd03a895
Create Date: 2026-01-03 22:16:01.696779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12898b16369'
down_revision = '731fdd03a895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_column('jenis_kebutuhan')

    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.drop_column('gambar_barang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengajuan_barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar_barang', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_kebutuhan', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
