"""ubah kolom pada donasi jadi status pengiriman

Revision ID: c48c240183db
Revises: bfaa8099b029
Create Date: 2025-10-16 12:15:57.819489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c48c240183db'
down_revision = 'bfaa8099b029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pengiriman', sa.Enum('pick_up', 'delivered', 'delivering', 'cancelled', 'done', 'rejected', name='metode_enum'), nullable=True))
        batch_op.drop_column('metode_pengiriman')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metode_pengiriman', postgresql.ENUM('pick_up', 'delivered', 'delivering', 'cancelled', 'done', 'rejected', name='metode_enum'), autoincrement=False, nullable=True))
        batch_op.drop_column('status_pengiriman')

    # ### end Alembic commands ###
