"""initial migration

Revision ID: cdd2319ca02b
Revises: 
Create Date: 2025-08-26 19:40:16.730260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd2319ca02b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('login_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('donatur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('login_stamp', sa.DateTime(), nullable=True),
    sa.Column('register_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('login_stamp', sa.DateTime(), nullable=True),
    sa.Column('register_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('barang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_donatur', sa.Integer(), nullable=True),
    sa.Column('nama_barang', sa.String(length=100), nullable=False),
    sa.Column('gambar_barang', sa.String(length=200), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.Column('tanggal_approve', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_donatur'], ['donatur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_diri_penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penghasilan_perbulan', sa.Integer(), nullable=False),
    sa.Column('jumlah_tanggungan', sa.Integer(), nullable=False),
    sa.Column('status_tempat_tinggal', sa.String(length=100), nullable=False),
    sa.Column('jumlah_kendaraan', sa.Integer(), nullable=False),
    sa.Column('jenis_kebutuhan', sa.String(length=100), nullable=False),
    sa.Column('id_penerima', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_penerima'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis_donasi', sa.String(length=100), nullable=False),
    sa.Column('jumlah_donasi', sa.String(length=100), nullable=False),
    sa.Column('tanggal_donasi', sa.DateTime(), nullable=True),
    sa.Column('tanggal_approve', sa.DateTime(), nullable=True),
    sa.Column('id_donatur', sa.Integer(), nullable=False),
    sa.Column('id_penerima', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_donatur'], ['donatur.id'], ),
    sa.ForeignKeyConstraint(['id_penerima'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasil_rekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_penerima', sa.Integer(), nullable=False),
    sa.Column('id_data_diri_penerima', sa.Integer(), nullable=False),
    sa.Column('layak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_data_diri_penerima'], ['data_diri_penerima.id'], ),
    sa.ForeignKeyConstraint(['id_penerima'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasil_rekomendasi')
    op.drop_table('donasi')
    op.drop_table('data_diri_penerima')
    op.drop_table('barang')
    op.drop_table('penerima')
    op.drop_table('donatur')
    op.drop_table('admin')
    # ### end Alembic commands ###
