"""rename table regiter_login to users

Revision ID: d2a0fc114505
Revises: bd29887b4e6a
Create Date: 2025-10-23 21:08:06.897518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a0fc114505'
down_revision = 'bd29887b4e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'donatur', 'penerima', name='role_enum'), server_default='admin', nullable=False),
    sa.Column('login_stamp', sa.DateTime(), nullable=True),
    sa.Column('register_stamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('rejected', 'approved', 'pending', name='permission_enum'), server_default='pending', nullable=False),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('rejected_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    #op.drop_table('register_login')
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('barang_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_donatur'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('data_diri_penerima_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('donasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('donasi_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['id_penerima'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hasil_klasifikasi_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hasil_rekomendasi_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifikasi_id_donatur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_donatur'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifikasi_id_donatur_fkey'), 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_rekomendasi_id_user_fkey'), 'register_login', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hasil_klasifikasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hasil_klasifikasi_id_user_fkey'), 'register_login', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('donasi_id_donatur_fkey'), 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('donasi_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('data_diri_penerima', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('data_diri_penerima_id_user_fkey'), 'register_login', ['id_user'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('barang_id_donatur_fkey'), 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')

    op.create_table('register_login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('login_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('register_stamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('approved_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('register_login_pkey')),
    sa.UniqueConstraint('email', name=op.f('register_login_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('register_login_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
