"""rename kolom table dokumentasi

Revision ID: d7135f3722d6
Revises: d8670ef6eb5f
Create Date: 2025-12-08 16:26:03.220260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7135f3722d6'
down_revision = 'd8670ef6eb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_dokumentasi', sa.DateTime(), nullable=True))
        batch_op.drop_column('tanggal_dokumendasi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_dokumendasi', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('tanggal_dokumentasi')

    # ### end Alembic commands ###
