"""hapus pasif delete

Revision ID: d79f99086104
Revises: 933e323d8099
Create Date: 2025-09-25 16:05:04.428004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79f99086104'
down_revision = '933e323d8099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.alter_column('skor',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.drop_column('pasif_deleter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasif_deleter', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.alter_column('skor',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
