"""tambah kolom file_name di table dokumentasi

Revision ID: d8670ef6eb5f
Revises: 14525fd0bdd9
Create Date: 2025-12-04 15:36:24.227475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8670ef6eb5f'
down_revision = '14525fd0bdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
