"""rename kolom id_donatur do table dokumentasi

Revision ID: ddee6fe64dcb
Revises: 39630b33a608
Create Date: 2025-12-09 13:21:24.712993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddee6fe64dcb'
down_revision = '39630b33a608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_donatur', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('dokumentasi_penerima_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('penerima_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dokumentasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penerima_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dokumentasi_penerima_id_fkey'), 'data_diri_penerima', ['penerima_id'], ['id'])
        batch_op.drop_column('id_donatur')

    # ### end Alembic commands ###
