"""rename id_penerima to id_donatur

Revision ID: e4ebb07e0304
Revises: 52b11b3ddba1
Create Date: 2025-10-12 15:52:22.159132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ebb07e0304'
down_revision = '52b11b3ddba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_donatur', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('notifikasi_id_penerima_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_penerima')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifikasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penerima', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifikasi_id_penerima_fkey'), 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_donatur')

    # ### end Alembic commands ###
