"""ubah nama kolom dari table hasil rekomendasi layak jadi skor

Revision ID: e71e04d0fcab
Revises: 4b97a0655bf8
Create Date: 2025-09-06 18:19:12.270692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71e04d0fcab'
down_revision = '4b97a0655bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skor', sa.Integer(), nullable=True))
        batch_op.drop_column('layak')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layak', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('skor')

    # ### end Alembic commands ###
