"""tambahkan id_penerima pada table_donasi

Revision ID: ecb52da31ace
Revises: 299a44e47065
Create Date: 2025-10-10 10:18:27.145779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb52da31ace'
down_revision = '299a44e47065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_donatur', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_penerima', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('donasi_id_user_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'register_login', ['id_donatur'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'register_login', ['id_penerima'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('donasi_id_user_fkey'), 'register_login', ['id_user'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_penerima')
        batch_op.drop_column('id_donatur')

    # ### end Alembic commands ###
